version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - sbt docker:publishLocal
  post_build:
    commands:
      - docker image tag play-example:1.0-SNAPSHOT "$IMAGE_URI"
      - docker image push "$IMAGE_URI"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_NAME" "$IMAGE_URI" > images.json
artifacts:
  files: images.json
cache:
  paths:
    - /root/.cache/**/*
    - /root/.coursier/**/*
    - /root/.m2/**/*
    - /root/.sbt/**/*
    - /root/.ivy2/**/*
    - /root/.pip/**/*
